name: ov7a

lsi: false
highlighter: rouge
gist:
  noscript: false
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

paginate: 10
paginate_path: "/mini_posts/page:num/"
paginate_first_page: "/mini_posts"

blog:
  paginate: 5
  paginate_path: "/blog/page:num/"
  paginate_first_page: "/blog"

theme: minima
date_format: "%d.%m.%Y"
lang: ru

future: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-commonmark-ghpages
  - jekyll-feed
  - jekyll-redirect-from

tag_page:
  - /blog/tags.html

defaults:
  - scope:
      path: "assets/gags"
    values:
      image: true
      gag: true
  - scope:
      path: "assets/puzzles/game00"
    values:
      image: true
      puzzle_game00: true
  - scope:
      path: "assets/puzzles/game01"
    values:
      image: true
      puzzle_game01: true
  - scope:
      path: "assets/puzzles/game02"
    values:
      image: true
      puzzle_game02: true
  - scope:
      path: "assets/puzzles/game03"
    values:
      image: true
      puzzle_game03: true
  - scope:
      path: "assets/puzzles/game04"
    values:
      image: true
      puzzle_game04: true
  - scope:
      path: "assets/puzzles/game05"
    values:
      image: true
      puzzle_game05: true

exclude:
  - moving_dom/src*
  - moving_dom/Cargo*

