name: ov7a

lsi: false
highlighter: rouge
gist:
  noscript: false
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

pagination:
  enabled: true
  permalink: '/page:num/'
  title: ':title'
  sort_reverse: true

theme: minima
date_format: "%d.%m.%Y"
lang: ru

future: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-commonmark-ghpages
  - jekyll-feed
  - jekyll-redirect-from

tag_page:
  - /blog/tags.html

defaults:
  - scope:
      path: "assets/gags"
    values:
      image: true
      gag: true
  - scope:
      path: "assets/puzzles/game00"
    values:
      image: true
      puzzle_game00: true
  - scope:
      path: "assets/puzzles/game01"
    values:
      image: true
      puzzle_game01: true
  - scope:
      path: "assets/puzzles/game02"
    values:
      image: true
      puzzle_game02: true
  - scope:
      path: "assets/puzzles/game03"
    values:
      image: true
      puzzle_game03: true
  - scope:
      path: "assets/puzzles/game04"
    values:
      image: true
      puzzle_game04: true
  - scope:
      path: "assets/puzzles/game05"
    values:
      image: true
      puzzle_game05: true
  - scope:
      path: "_posts/mini_posts"
    values:
      category: mini_post 

exclude:
  - moving_dom/src*
  - moving_dom/Cargo*
  - vendor/**
  - bundle/**
