name: ov7a

lsi: false
highlighter: rouge
gist:
  noscript: false
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]

pagination:
  enabled: true
  permalink: '/page:num/'
  title: ':title'
  sort_reverse: true

theme: minima
date_format: "%d.%m.%Y"
lang: ru

future: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-commonmark-ghpages
  - jekyll-feed
  - jekyll-redirect-from

tag_page:
  - /blog/tags.html

defaults:
  - scope:
      path: "assets/gags"
    values:
      gag_image: true
  - scope:
      path: "assets/puzzles"
    values:
      puzzle_image: true    
  - scope:
      path: "_posts/mini_posts"
    values:
      category: mini_post 

exclude:
  - moving_dom/src*
  - moving_dom/Cargo*
  - vendor/**
  - bundle/**
