name: "Check markdown links"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: actions/jekyll-build-pages@v1    

      - name: Check links
        uses: lycheeverse/lychee-action@v2.0.0
        with:
          # excluded # and ## as they used in the gallery
          args: >
            --no-progress --include-fragments --offline '_site' 
            --exclude '##?$' 
